const GENERATION = {
    FETCH: 'GENERATION_FETCH',
    FETCH_ERROR: 'GENERATION_ERROR',
    FETCH_SUCCESS: 'GENERATION_SUCCESS',
};

const DRAGON = {
    FETCH: 'DRAGON_FETCH',
    FETCH_ERROR: 'DRAGON_ERROR',
    FETCH_SUCCESS: 'DRAGON_SUCCESS',
}

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
}

export {GENERATION, DRAGON, ACCOUNT}