const GENERATION = {
    FETCH: 'GENERATION_FETCH',
    FETCH_ERROR: 'GENERATION_ERROR',
    FETCH_SUCCESS: 'GENERATION_SUCCESS',
};

const DRAGON = {
    FETCH: 'DRAGON_FETCH',
    FETCH_ERROR: 'DRAGON_ERROR',
    FETCH_SUCCESS: 'DRAGON_SUCCESS',
}

export {GENERATION, DRAGON}